# 1.- Dependencies
FROM node:22.12-alpine3.19 as deps

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install


# 2.- Builder
FROM node:22.12-alpine3.19 as build

WORKDIR /usr/src/app

# Copiar desde deps los módulos de node
COPY --from=deps /usr/src/app/node_modules ./node_modules
# Copiar todo el código fuente de la app
COPY . .

# RUN npm run test
RUN npx prisma generate
RUN npm run build
RUN npm ci -f --only=production && npm cache clean --force


# 3.- Crear la imagen final de Docker
FROM node:22.12-alpine3.19 as prod

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/prisma ./prisma
COPY --from=build /usr/src/app/prisma.config.ts .  

ENV NODE_ENV=production

RUN chown -R node:node /usr/src/app

USER node

EXPOSE 3001

# 👇 Corre migrate deploy antes de levantar la app
CMD ["sh", "-c", "npx prisma migrate deploy && node dist/src/main.js"]